pipeline:
  name: test-ab
  identifier: testab
  projectIdentifier: Wakanda
  orgIdentifier: bootcampjune2026
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubconnectab
        build: <+input>
  stages:
    - stage:
        name: clone
        identifier: clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      pip install requests pyyaml -q
                      python -c "import requests; r = requests.get('https://apidocs.harness.io'); print('Spec reachable:', r.status_code)"
